//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int UpdateGUILed {
            get {
                return ((int)(this["UpdateGUILed"]));
            }
            set {
                this["UpdateGUILed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\PRODUCTION\\Programs\\R2")]
        public string RSAUserRecipePath {
            get {
                return ((string)(this["RSAUserRecipePath"]));
            }
            set {
                this["RSAUserRecipePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\Github\\PPASw\\src\\GUI\\bin\\Debug\\splash.jpg")]
        public string SplashScreenFilepath {
            get {
                return ((string)(this["SplashScreenFilepath"]));
            }
            set {
                this["SplashScreenFilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opc.tcp://172.31.20.101:48011")]
        public string OpcClient_1_URI {
            get {
                return ((string)(this["OpcClient_1_URI"]));
            }
            set {
                this["OpcClient_1_URI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opc.tcp://localhost:6000")]
        public string OpcClient_2_URI {
            get {
                return ((string)(this["OpcClient_2_URI"]));
            }
            set {
                this["OpcClient_2_URI"] = value;
            }
        }
    }
}
